version: '3.8'

services:
  client:
    build: 
      context: ./client/
    container_name: portfolio_client
    ports:
      - "4028:80"
      # - "443:443"
    restart: always

  admin:
    build:
      context: ./admin/
    container_name: portfolio_admin
    env_file:
      - ./admin/.env.templete
    ports:
      - "4050:80"
    restart: always