name: Admin Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'admin/**'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./admin
        run: npm install

      - name: Build admin
        working-directory: ./admin
        run: npm run build
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Prepare directories on VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            if [ ! -d "/home/ubuntu/deploiment/portfolio/admin" ]; then
              mkdir -p /home/ubuntu/deploiment/portfolio/admin
              touch /home/ubuntu/deploiment/portfolio/admin/.env.templete
              echo "Admin directory created"
            else
              echo "Admin directory already exists, skipping"
            fi
            if [ ! -f "/home/ubuntu/deploiment/portfolio/server/.env" ]; then
              mkdir -p /home/ubuntu/deploiment/portfolio/server
              touch /home/ubuntu/deploiment/portfolio/server/.env
              echo "server .env created"
            fi

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "admin/Dockerfile,admin/nginx/"
          target: "/home/ubuntu/deploiment/portfolio/admin/"
          strip_components: 1

      - name: Copy build files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "admin/dist/"
          target: "/home/ubuntu/deploiment/portfolio/admin/"
          strip_components: 1

      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/deploiment/portfolio/"

      - name: SSH & Deploy Docker Compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/deploiment/portfolio/
            docker-compose up -d --build --no-deps admin